# Projekt 5 - Numerická lineární algebra 1
**Autor:** Kassymbekova Diana
**Příklad č. 1:** LUPQ rozklad matice s úplnou pivotizací
**Příklad č. 3:** Programové ověření ručního výpočtu

## Zadání
Naprogramujte v programovacím jazyce Python LUPQ rozklad matice $A \in \mathbb{R}^{n \times n}$ s úplnou pivotizací, tzn. $PAQ = LU$. 
Algoritmus hledá v každém kroku $k$ maximální prvek v absolutní hodnotě v podmatici $A(k:n, k:n)$ a provádí příslušné výměny řádků a sloupců.

In [4]:
import numpy as np

def lupq_decomposition(A_input):
    """
    Funkce provádí LUPQ rozklad matice A s úplnou pivotizací.
    Vrací upravenou matici A (obsahující L a U), a vektory p, q pro permutace.
    """
    A = np.array(A_input, dtype=float)
    n = A.shape[0]
    
    p = np.arange(n)
    q = np.arange(n)
    
    for k in range(n - 1):
        submatrix = np.abs(A[k:n, k:n])

        # Hledáme maximální prvek a jeho indexy
        max_val = -1
        max_idx = (0, 0)
        for i in range(submatrix.shape[0]):
            for j in range(submatrix.shape[1]):
                if submatrix[i, j] > max_val:
                    max_val = submatrix[i, j]
                    max_idx = (i, j)
        
        mu = k + max_idx[0]
        lam = k + max_idx[1]
        
        # Permutace P
        A[[k, mu], :] = A[[mu, k], :]
        p[[k, mu]] = p[[mu, k]]
        
        # Permutace Q
        A[:, [k, lam]] = A[:, [lam, k]]
        q[[k, lam]] = q[[k, lam]]
        q[[k, lam]] = q[[lam, k]]
        
        # Gaussova eliminace
        if A[k, k] != 0:
            rows = slice(k + 1, n)
            # Výpočet matice L
            A[rows, k] = A[rows, k] / A[k, k]
            # Výpočet matice U
            A[rows, rows] = A[rows, rows] - np.outer(A[rows, k], A[k, rows])
            
    return A, p, q

## Ověření funkčnosti
Vytvoříme pomocnou funkci pro extrakci matic $L, U, P, Q$ z výsledku, abychom mohli ověřit vztah $PAQ = LU$.

In [5]:
def verify_lupq(A_orig, A_res, p, q):
    n = A_orig.shape[0]
    
    # Extrakce L
    L = np.tril(A_res, -1) + np.eye(n)
    
    # Extrakce U 
    U = np.triu(A_res)
    
    # Sestavení permutačních matic P a Q
    P = np.eye(n)[p]
    Q = np.eye(n)[:, q]
    
    # Kontrola PAQ = LU
    PAQ = P @ A_orig @ Q
    LU = L @ U
    
    print("Matice PAQ:\n", PAQ)
    print("\nMatice LU:\n", LU)
    print("\nRozdíl (norma):", np.linalg.norm(PAQ - LU))

# Test na náhodné matici
A_test = np.random.rand(4, 4)
A_res, p, q = lupq_decomposition(A_test)
verify_lupq(A_test, A_res, p, q)

Matice PAQ:
 [[0.96695747 0.13071841 0.49153814 0.44922954]
 [0.46397762 0.63076347 0.00620324 0.75889166]
 [0.44606491 0.20814933 0.71360904 0.53189168]
 [0.56364503 0.46841205 0.62111533 0.48805633]]

Matice LU:
 [[0.96695747 0.13071841 0.49153814 0.44922954]
 [0.46397762 0.63076347 0.00620324 0.75889166]
 [0.44606491 0.20814933 0.71360904 0.53189168]
 [0.56364503 0.46841205 0.62111533 0.48805633]]

Rozdíl (norma): 0.0


## Zadání
Zvolte libovolnou vhodnou matici $A \in \mathbb{R}^{4 \times 4}$ a ručně vypočítejte její LUPQ rozklad s použitím algoritmu z 1. příkladu. Matice musí být zvolena tak, aby bylo nutné provést alespoň jednu pivotizaci. Správnost výpočtu následně ověřte v Pythonu.

In [6]:
# Definice matice
A_manual = np.array([
    [2, 3, 0, 0],
    [4, 2, 0, 0],
    [0, 0, 2, 0],
    [0, 0, 0, 2]
], dtype=float)

# Spuštění algoritmu
A_res, p, q = lupq_decomposition(A_manual)

# Výpis výsledků
verify_lupq(A_manual, A_res, p, q)

Matice PAQ:
 [[4. 2. 0. 0.]
 [2. 3. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]

Matice LU:
 [[4. 2. 0. 0.]
 [2. 3. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]

Rozdíl (norma): 0.0
